# Generated by Django 3.1.7 on 2021-02-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
    ]
