# Generated by Django 3.1.7 on 2021-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_product_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(default='https://www.camerathudo.com/template/default/images/no_image.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.TextField(default='Неизвестно'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(default='https://www.ozon.ru/'),
            preserve_default=False,
        ),
    ]
