# Generated by Django 3.1.7 on 2021-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210228_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.CharField(max_length=120, unique=True, verbose_name='Запрос')),
                ('amount', models.CharField(default=0, max_length=120, verbose_name='Количество')),
            ],
        ),
    ]
