# Generated by Django 3.1.7 on 2021-03-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210315_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Статистика поисковых запросов', 'verbose_name_plural': 'Статистика поисковых запросов'},
        ),
    ]
